{
 "title": "Liberando productos KC Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(kube_deployment_labels , deployment)"
   },
   {
    "name": "pod",
    "query": "label_values(kube_pod_info {pod=~\"$deployment.*\" },pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU use",
   "type": "graph",
   "description": "Uso de CPU sumando (de todos los pods del deployment seleccionados en la variable)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_cpu_usage_seconds_total {container_label_io_kubernetes_container_name=\"POD\",  container_label_io_kubernetes_pod_name=~\"$pod\"}) by (container_label_io_kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Total memory in use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes {container_label_io_kubernetes_container_name=\"POD\", container_label_io_kubernetes_pod_name=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "POD restart count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_tasks_state{ container_label_io_kubernetes_pod_name=~\"$pod\",state=\"running\",container_label_io_kubernetes_container_name=\"POD\"}"
    }
   ]
  }
 ]
}