apiVersion: v1
kind: Service
metadata:
  name: cadvisor
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30001
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: cadvisor

