apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: kube-state-metrics
