global:
  scrape_interval:     15s

rule_files:
  - "/etc/prometheus/my_rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
           - localhost:9093

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "kube-state-metrics"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:8080"]
  - job_name: "cadvisor"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:8081"]
